# Generated by Django 3.0.6 on 2020-07-02 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attendance_percentage', models.FloatField()),
                ('student_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sgnaltest.Student')),
            ],
        ),
    ]
