# Generated by Django 3.0.6 on 2020-07-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgnaltest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Attendance_percentage',
            field=models.FloatField(default=75),
        ),
    ]
